---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "github_actions"
      - "no_ci_cd_run"
    commit-message:
      prefix: "ci"
    groups:
      patch-minor-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
    commit-message:
      prefix: "build"
    groups:
      patch-minor-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "maven"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
    commit-message:
      prefix: "build"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "io.vavr:vavr"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
    commit-message:
      prefix: "build"
    groups:
      patch-minor-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
    commit-message:
      prefix: "build"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "faker"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
    commit-message:
      prefix: "build"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
