FROM python:3.10-slim-bookworm@sha256:dd9ccd42990116c1f31cb0cc649a1a9321c6afa110494e222887fdc8412d0e1f
LABEL org.opencontainers.image.source=https://github.com/aps831/htmx-thymeleaf-jersey-jetty-test
HEALTHCHECK NONE
ARG BUILDKIT_SBOM_SCAN_CONTEXT=true
ARG BUILDKIT_SBOM_SCAN_STAGE=true
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd -g "${GROUP_ID}" appuser && useradd --create-home --no-log-init -u "${USER_ID}" -g "${GROUP_ID}" appuser
USER appuser
WORKDIR /app
ENV VIRTUAL_ENV=/app/.venv-container \
    PATH="/app/.venv-container/bin:$PATH"
COPY .venv-container .venv-container
COPY app .
CMD ["python", "app.py"]
