FROM python:3.13-slim-bookworm@sha256:56a11364ffe0fee3bd60af6d6d5209eba8a99c2c16dc4c7c5861dc06261503cc
LABEL org.opencontainers.image.source=https://github.com/aps831/workflows-testbed-python
HEALTHCHECK NONE
ARG BUILDKIT_SBOM_SCAN_CONTEXT=true
ARG BUILDKIT_SBOM_SCAN_STAGE=true
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd -g "${GROUP_ID}" appuser && useradd --create-home --no-log-init -u "${USER_ID}" -g "${GROUP_ID}" appuser
USER appuser
WORKDIR /app
ENV VIRTUAL_ENV=/app/.venv-container \
    PATH="/app/.venv-container/bin:$PATH"
COPY .venv-container .venv-container
COPY app .
CMD ["python", "app.py"]
