FROM python:3.13-slim-bookworm@sha256:fac773db136dc036c6352d7c0fc70f8d9fab78399aac6a282064d1cf581fde3b
LABEL org.opencontainers.image.source=https://github.com/aps831/htmx-thymeleaf-jersey-jetty-test
HEALTHCHECK NONE
ARG BUILDKIT_SBOM_SCAN_CONTEXT=true
ARG BUILDKIT_SBOM_SCAN_STAGE=true
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd -g "${GROUP_ID}" appuser && useradd --create-home --no-log-init -u "${USER_ID}" -g "${GROUP_ID}" appuser
USER appuser
WORKDIR /app
ENV VIRTUAL_ENV=/app/.venv-container \
    PATH="/app/.venv-container/bin:$PATH"
COPY .venv-container .venv-container
COPY app .
CMD ["python", "app.py"]
