---
# yaml-language-server: =https://json.schemastore.org/github-workflow.json
name: Bitbucket Mirror
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
permissions:
  contents: read
  issues: read
  pull-requests: read
jobs:
  mirror:
    uses: aps831/workflows/.github/workflows/bitbucket-mirror.yaml@master
    with:
      username: aps831-github
      repositoryname: workflows-testbed-python
    secrets:
      BITBUCKET_SSH_PRIVATE_KEY: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
