---
name: Build and Publish Package
on:
  push:
    branches:
      - "master"
      - "prerelease"
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  attestations: write
  id-token: write
jobs:
  build:
    uses: aps831/workflows/.github/workflows/build-and-publish-poetry-docker-image-artifact-v2.yaml@master
    with:
      image-name: "workflows-testbed-python"
      dockerfile-build: "Dockerfile.build"
      dockerfile-prod: "Dockerfile.prod"
      volumes: |
        .:/app
      build-command: poetry poe build
      test-command: poetry poe e2e
      templated-files: README.tpl.md
      python-version: 3.13.3
      poetry-version: 2.1.2
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # GITHUB_TOKEN will not fire 'release' and 'registry_package' events
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
