---
name: Grype SBOM Scan
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 22 * *"
  release:
    types:
      - published
permissions:
  contents: read
jobs:
  scan:
    uses: aps831/workflows/.github/workflows/grype-sbom-scan.yaml@master
    with:
      sbom-name: "cyclonedx.json$"
      release-tag: ${{ github.event.release.tag_name }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
