---
name: Trivy Image Scan Dispatched
on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 1 * *
permissions:
  packages: read
jobs:
  scan:
    uses: aps831/workflows/.github/workflows/trivy-image-scan-dispatched.yaml@master
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
