---
name: Trunk Check
on:
  pull_request: {}
permissions:
  contents: read
  checks: write
jobs:
  check:
    name: trunk check
    uses: aps831/workflows/.github/workflows/trunk.yaml@master
    with:
      python-version: 3.13.3
      poetry-version: 2.1.2
      install-deps-script: poetry install --no-root --no-ansi --no-interaction
